# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: R_arm
  joint_model_group_pose: "Home "
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - omo_Lj
    - shouder_Lj
    - rotate_Lj
    - hand_Lj
    - rest_Lj
    - omo_Rj
    - shoulder_Rj
    - rotate_Rj
    - hand_Rj
    - rest_Rj
    - wheel_Lj
    - wheel_Lj1
    - wheel_Rj
    - wheel_Rj1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
r_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - shoulder_Rj
    - rotate_Rj
    - hand_Rj
    - rest_Rj
    - rest_Rj
  gains:
    shoulder_Rj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rotate_Rj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hand_Rj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rest_Rj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rest_Rj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
l_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - rest_Lj
    - shouder_Lj
    - rotate_Lj
    - hand_Lj
    - rest_Lj
  gains:
    rest_Lj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shouder_Lj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rotate_Lj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hand_Lj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rest_Lj:
      p: 100
      d: 1
      i: 1
      i_clamp: 1